<div>
    <div class='default'>
	<h2>{t}How to get started{/t}</h2>
	<p>
	{t}This seems to be the first time you run GOsa on this system. To start the GOsa web interface you need a working configuration file, which can be generated by this wizard.{/t}
	</p>

	<p>
      {t}What you need to generate a configuration file:{/t}
	</p>

      <ul>
       <li>{t}The hostname of your LDAP server{/t}</li>
       <li>{t}Installed GOsa and supplementary schema{/t}</li>
       <li>{t}The LDAP base of your LDAP directory{/t}</li>
       <li>{t}The DN and the password of the LDAP administration user{/t}</li>
      </ul>
	
	<p>
      {t}If you've collected the needed information, unlock the setup process like shown in the next paragraph.{/t}
	</p>

    <hr>
	<h2>{t}Starting the setup{/t}</h2>
	<p>
	{t}For security reasons you need to authenticate the installation by creating the file '/tmp/gosa.auth', containing the current session ID on the servers local filesystem. This can be done by executing the following command:{/t}
	</p>
	<tt>
	echo -n <b>{$auth_id}</b> &gt; {$path}
	</tt>
	<p>
	{t}Click the 'Next' button when you've finished.{/t}
	</p>
     </div>
</div>
