#!/bin/bash

test -d "$1" && exec >"$1/packages.xml"

update="$(LC_ALL=C apt-get --dry-run dist-upgrade| sed -r -n 's/^Inst ([^ ]+) [^(]*\(([^ ]+).*/  "\1") echo "    <update>\2<\/update>" ;;/p')"
update="u() { case \"\$1\" in
$update
esac
}
"

eval "$update"

timestamp="$(date +%Y%m%d_%H%M%S)"
macaddress="$(ip link show | sed -r -n 's/^.*link\/[^l][^ ]* ([^ ]+).*/\1/p'|head -n 1)"
hostname="$(hostname)"
ipaddress="$(LC_ALL=C host $(hostname) | sed -r -n 's/^.*has address (.*)/\1/p' | head -n 1)"

echo "<audit>
  <timestamp>$timestamp</timestamp>"
test -n "$macaddress" && echo "  <macaddress>$macaddress</macaddress>"
echo "  <hostname>$hostname</hostname>"
test -n "$ipaddress" && echo "  <ipaddress>$ipaddress</ipaddress>"


LC_ALL=C COLUMNS=1000 dpkg -l|sed -r -n '6,$s/^([^ ]+) +([^ ]+) +([^ ]+).*/\1 \2 \3/p'|
while read -r status key version ; do
echo "
  <entry>
    <key>$key</key>
    <version>$version</version>
    <status>$status</status>"
    u "$key"
echo "  </entry>"

done

echo "
</audit>"