gosa-si-server											usr/sbin
server.conf													etc/gosa-si
modules/ClientPackages.pm						usr/lib/gosa-si/modules
modules/GosaPackages.pm							usr/lib/gosa-si/modules
modules/ArpHandler.pm								usr/lib/gosa-si/modules
modules/oui.txt											usr/lib/gosa-si/modules
modules/ServerPackages.pm						usr/lib/gosa-si/modules
server/events/gosaTriggered.pm			usr/lib/gosa-si/server/GosaPackages
server/events/siTriggered.pm				usr/lib/gosa-si/server/ClientPackages
server/events/clMessages.pm					usr/lib/gosa-si/server/ClientPackages
server/events/databases.pm					usr/lib/gosa-si/server/GosaPackages
server/events/databases.pm					usr/lib/gosa-si/server/ServerPackages
server/events/logHandling.pm				usr/lib/gosa-si/server/GosaPackages
server/events/logHandling.pm				usr/lib/gosa-si/server/ServerPackages
server/events/server_server_com.pm 	usr/lib/gosa-si/server/ServerPackages

