#!/bin/sh -e

#DEBHELPER#

# We exit unless the package is being configured
case "$1" in
        abort*upgrade)         exit 0;;
        abort*remove)          exit 0;;
        abort*deconfigure)     exit 0;;
        configure) ;;
        *)                     exit 0;
esac

# Fix permission
#[ -f /etc/gosa-si/server.conf ] && chmod go-rwx /etc/gosa-si/server.conf

# start daemon
#invoke-rc.d gosa-si-server start

exit 0
