#!/bin/bash
pidfile="$(sed -n 's/^pid-file *= *\([^ ]*\)/\1/p' /etc/gosa-si/server.conf)"
test -z "$pidfile" && pidfile=/var/run/gosa-si-server.pid

foreground="0"

args=()
while [ $# != 0 ]; do
  if [ "$1" = "-f" ]; then
    foreground="1"
    shift
    continue
  fi
  args=("${args[@]}" "$1")
  shift
done

rm -f "$pidfile"

# We must call /usr/lib/gosa-si-server because the binary has to be named gosa-si-server,
# because start-stop-daemon tests this name.
# It is not enough to pass argv[0]=gosa-si-server via exec.

if [ $foreground = 1 ]; then
  echo "$BASHPID" >"$pidfile"
  exec /usr/lib/gosa-si-server "${args[@]}"
else
  (
    trap "" SIGHUP
    echo "$BASHPID" >"$pidfile"
    exec &>- <- setsid /usr/lib/gosa-si-server "${args[@]}"
  )&
fi
