
=head1 NAME

update-gosa - class cache updater and plugin manager for GOsa

=head1 SYNOPSIS

update-gosa [OPTION] 

=head1 DESCRIPTION

update-gosa is a script that help you to manage your gosa instance

=over 5

=item B<install dsc>       Install the plugin using the dsc information placed in the plugin source directory.

=item B<remove plugin>     Remove the plugin named "plugin" from the current configuration.

=item B<list>              Lists installed plugins

=item B<rescan-i18n>       Rebuilds the translations

=item B<rescan-classes>    Rebuilds the class list

=back

=head1 BUGS

Please report any bugs, or post any suggestions, to the GOsa mailing list <gosa-devel@oss.gonicus.de> or to <https://oss.gonicus.de/labs/gosa>


=head1 LICENCE AND COPYRIGHT

This code is part of GOsa (L<http://www.gosa-project.org>)

Copyright (C) 2003-2009 GONICUS GmbH

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut

